### ISSUE TITLE
cant compile on 4.13

### ISSUE THREAD

**Issue by TonyStark** [muratdemirtas/MT7601_STA_AP#2]
```
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:2164:9: warning: unused variable ‘macAddr’ [-Wunused-variable]
  UINT32 macAddr = 0, macValue = 0;
         ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c: In function ‘RtmpOSIRQRelease’:
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:2300:21: warning: unused variable ‘net_dev’ [-Wunused-variable]
  struct net_device *net_dev = (struct net_device *)pNetDev;
                     ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c: In function ‘RtmpOsFreeSpinLock’:
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:4319:8: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
  pLock = (OS_NDIS_MINIPORT_TIMER *) (pLockOrg->pContent);
        ^
In file included from /home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/rtmp_os.h:48:0,
                 from /home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/rtmp_comm.h:69,
                 from /home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:35:
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c: In function ‘RtmpOsPktTailAdjust’:
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/os/rt_linux.h:943:36: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   ((RTPKT_TO_OSPKT(_pkt))->tail) = (PUCHAR)((_start) + (_len))
                                    ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/os/rt_linux.h:967:2: note: in expansion of macro ‘SET_OS_PKT_DATATAIL’
  SET_OS_PKT_DATATAIL(_pkt, GET_OS_PKT_DATATAIL(_pkt), (-_removedTagLen)); \
  ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:5209:2: note: in expansion of macro ‘OS_PKT_TAIL_ADJUST’
  OS_PKT_TAIL_ADJUST(pNetPkt, removedTagLen);
  ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/os/rt_linux.h:943:34: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
   ((RTPKT_TO_OSPKT(_pkt))->tail) = (PUCHAR)((_start) + (_len))
                                  ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/os/rt_linux.h:967:2: note: in expansion of macro ‘SET_OS_PKT_DATATAIL’
  SET_OS_PKT_DATATAIL(_pkt, GET_OS_PKT_DATATAIL(_pkt), (-_removedTagLen)); \
  ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:5209:2: note: in expansion of macro ‘OS_PKT_TAIL_ADJUST’
  OS_PKT_TAIL_ADJUST(pNetPkt, removedTagLen);
  ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c: In function ‘RtmpThreadPidKill’:
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/include/os/rt_linux.h:532:37: error: implicit declaration of function ‘kill_pid’ [-Werror=implicit-function-declaration]
 #define KILL_THREAD_PID(_A, _B, _C) kill_pid((_A), (_B), (_C))
                                     ^
/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.c:5311:9: note: in expansion of macro ‘KILL_THREAD_PID’
  return KILL_THREAD_PID(PID, SIGTERM, 1);
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:316: recipe for target '/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.o' failed
make[3]: *** [/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux/../../os/linux/rt_linux.o] Error 1
Makefile:1550: recipe for target '_module_/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux' failed
make[2]: *** [_module_/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src/os/linux] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.13.0-43-generic'
Makefile:510: recipe for target 'osutil' failed
make[1]: *** [osutil] Error 2
make[1]: Leaving directory '/home/stark/learn/mi/muratdemirtas/MT7601_STA_AP/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

```
